In [1]:
%logstop
%logstart -rtq ~/.logs/dw.py append
%matplotlib inline
import matplotlib
import seaborn as sns
sns.set()
matplotlib.rcParams['figure.dpi'] = 144

Logging hadn't been started.

C:\Users\DELL\Anaconda3\lib\site-packages\IPython\core\magics\logging.py:130: UserWarning: Couldn't start log: [Errno 2] No such file or directory: 'C:\\Users\\DELL/.logs/dw.py'
  warn("Couldn't start log: %s" % sys.exc_info()[1])

In [2]:
from static_grader import grader

ModuleNotFoundError: No module named 'static_grader'

# DW Miniproject
## Introduction

The objective of this miniproject is to exercise your ability to wrangle tabular data set and aggregate large data sets into meaningful summary statistics. We'll work with the same medical data used in the `pw` miniproject but leverage the power of Pandas to more efficiently represent and act on our data.

## Downloading the data

We first need to download the data we'll be using from Amazon S3:

In [2]:
!mkdir dw-data
!wget http://dataincubator-wqu.s3.amazonaws.com/dwdata/201701scripts_sample.csv.gz -nc -P ./dw-data/
!wget http://dataincubator-wqu.s3.amazonaws.com/dwdata/201606scripts_sample.csv.gz -nc -P ./dw-data/
!wget http://dataincubator-wqu.s3.amazonaws.com/dwdata/practices.csv.gz -nc -P ./dw-data/
!wget http://dataincubator-wqu.s3.amazonaws.com/dwdata/chem.csv.gz -nc -P ./dw-data/

A subdirectory or file dw-data already exists.
'wget' is not recognized as an internal or external command,
operable program or batch file.
'wget' is not recognized as an internal or external command,
operable program or batch file.
'wget' is not recognized as an internal or external command,
operable program or batch file.
'wget' is not recognized as an internal or external command,
operable program or batch file.

## Loading the data

Similar to the `PW` miniproject, the first step is to read in the data. The data files are stored as compressed CSV files. You can load the data into a Pandas DataFrame by making use of the `gzip` package to decompress the files and Panda's `read_csv` methods to parse the data into a DataFrame. You may want to check the Pandas documentation for parsing [CSV](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html) files for reference.

For a description of the data set please, refer to the [PW miniproject](./pw.ipynb). **Note that all questions make use of the 2017 data only, except for Question 5 which makes use of both the 2017 and 2016 data.**

In [3]:
import pandas as pd
import numpy as np
import gzip

In [5]:
# load the 2017 data
scripts = pd. read_csv('./dw-data/201701scripts_sample.csv.gz')
scripts.head()

,practice,bnf_code,bnf_name,items,nic,act_cost,quantity
0,N85639,0106020C0,Bisacodyl_Tab E/C 5mg,1,0.39,0.47,12
1,N85639,0106040M0,Movicol Plain_Paed Pdr Sach 6.9g,1,4.38,4.07,30
2,N85639,0301011R0,Salbutamol_Inha 100mcg (200 D) CFF,1,1.50,1.40,1
3,N85639,0304010G0,Chlorphenamine Mal_Oral Soln 2mg/5ml,1,2.62,2.44,150
4,N85639,0401020K0,Diazepam_Tab 2mg,1,0.16,0.26,6

In [6]:
col_names=[ 'code', 'name', 'addr_1', 'addr_2', 'borough', 'village', 'post_code']
practices = pd.read_csv('./dw-data/practices.csv.gz', names= col_names)
practices.head()

,code,name,addr_1,addr_2,borough,village,post_code
0,A81001,THE DENSHAM SURGERY,THE HEALTH CENTRE,LAWSON STREET,STOCKTON ON TEES,CLEVELAND,TS18 1HU
1,A81002,QUEENS PARK MEDICAL CENTRE,QUEENS PARK MEDICAL CTR,FARRER STREET,STOCKTON ON TEES,CLEVELAND,TS18 2AW
2,A81003,VICTORIA MEDICAL PRACTICE,THE HEALTH CENTRE,VICTORIA ROAD,HARTLEPOOL,CLEVELAND,TS26 8DB
3,A81004,WOODLANDS ROAD SURGERY,6 WOODLANDS ROAD,NaN,MIDDLESBROUGH,CLEVELAND,TS1 3BE
4,A81005,SPRINGWOOD SURGERY,SPRINGWOOD SURGERY,RECTORY LANE,GUISBOROUGH,NaN,TS14 7DJ

In [7]:
chem = pd.read_csv('./dw-data/chem.csv.gz')
chem.head()

    CHEM SUB                                NAME
0  0101010A0                     Alexitol Sodium
1  0101010B0                          Almasilate
2  0101010C0                 Aluminium Hydroxide
3  0101010D0  Aluminium Hydroxide With Magnesium
4  0101010E0                        Hydrotalcite

Now that we've loaded in the data, let's first replicate our results from the `PW` miniproject. Note that we are now working with a larger data set so the answers will be different than in the `PW` miniproject even if the analysis is the same.

## Question 1: summary_statistics

In the `PW` miniproject we first calculated the total, mean, standard deviation, and quartile statistics of the `'items'`, `'quantity'`', `'nic'`, and `'act_cost'` fields. To do this we had to write some functions to calculate the statistics and apply the functions to our data structure. The DataFrame has a `describe` method that will calculate most (not all) of these things for us.

Submit the summary statistics to the grader as a list of tuples: [('act_cost', (total, mean, std, q25, median, q75)), ...]

In [8]:
scripts.describe()

               items            nic       act_cost       quantity
count  973193.000000  973193.000000  973193.000000  973193.000000
mean        9.133136      73.058915      67.986613     741.329835
std        29.204198     188.070257     174.401703    3665.426958
min         1.000000       0.000000       0.040000       0.000000
25%         1.000000       7.800000       7.330000      28.000000
50%         2.000000      22.640000      21.220000     100.000000
75%         6.000000      65.000000      60.670000     350.000000
max      2384.000000   16320.000000   15108.320000  577720.000000

In [9]:
fields = ['items', 'quantity', 'nic', 'act_cost']
total_row =scripts[fields].sum()

In [10]:
df_out = scripts[fields].describe().loc[['mean', 'std', '25%', '50%', '75%']]

In [11]:
df_out[:2]

          items     quantity         nic    act_cost
mean   9.133136   741.329835   73.058915   67.986613
std   29.204198  3665.426958  188.070257  174.401703

In [12]:
stats = pd.concat([total_row, df_out.T], axis=1)
print(stats)

                     0        mean          std    25%     50%     75%
items     8.888304e+06    9.133136    29.204198   1.00    2.00    6.00
quantity  7.214570e+08  741.329835  3665.426958  28.00  100.00  350.00
nic       7.110042e+07   73.058915   188.070257   7.80   22.64   65.00
act_cost  6.616410e+07   67.986613   174.401703   7.33   21.22   60.67

In [13]:
a = tuple(stats.loc['items'])
b = tuple(stats.loc['quantity'])
c = tuple(stats.loc['nic'])
d = tuple(stats.loc['act_cost'])

In [14]:
summary_stats = [('items',a), ('quantity',b), ('nic',c), ('act_cost',d)]

In [15]:
grader.score.dw__summary_statistics(summary_stats)

==================
Your score:  1.0
==================

## Question 2: most_common_item

We can also easily compute summary statistics on groups within the data. In the `pw` miniproject we had to explicitly construct the groups based on the values of a particular field. Pandas will handle that for us via the `groupby` method. This process is [detailed in the Pandas documentation](https://pandas.pydata.org/pandas-docs/stable/groupby.html).

Use `groupby` to calculate the total number of items dispensed for each `'bnf_name'`. Find the item with the highest total and return the result as `[(bnf_name, total)]`.

In [16]:
scripts.head()

,practice,bnf_code,bnf_name,items,nic,act_cost,quantity
0,N85639,0106020C0,Bisacodyl_Tab E/C 5mg,1,0.39,0.47,12
1,N85639,0106040M0,Movicol Plain_Paed Pdr Sach 6.9g,1,4.38,4.07,30
2,N85639,0301011R0,Salbutamol_Inha 100mcg (200 D) CFF,1,1.50,1.40,1
3,N85639,0304010G0,Chlorphenamine Mal_Oral Soln 2mg/5ml,1,2.62,2.44,150
4,N85639,0401020K0,Diazepam_Tab 2mg,1,0.16,0.26,6

In [17]:
total_items = scripts.groupby('bnf_name')['items'].sum()
total_items.head()

bnf_name
365 Film 10cm x 12cm VP Adh Film Dress      2
365 Non Adherent 10cm x 10cm Pfa Plas Fa    3
365 Non Adherent 10cm x 20cm Pfa Plas Fa    1
365 Non Woven Island 8cm x 10cm Adh Dres    1
365 Transpt Island 5cm x 7.2cm VP Adh Fi    2
Name: items, dtype: int64

In [18]:
max_value = total_items.max()
print(max_value)

218583

In [19]:
max_item = total_items.idxmax()
print(max_item)

Omeprazole_Cap E/C 20mg

In [20]:
most_common_item = [(max_item, max_value)]
print(most_common_item)

[('Omeprazole_Cap E/C 20mg', 218583)]

In [21]:
grader.score.dw__most_common_item(most_common_item)

==================
Your score:  1.0
==================

## Question 3: items_by_region

Now let's find the most common item by post code. The post code information is in the `practices` DataFrame, and we'll need to `merge` it into the `scripts` DataFrame. Pandas provides [extensive documentation](https://pandas.pydata.org/pandas-docs/stable/merging.html) with diagrammed examples on different methods and approaches for joining data. The `merge` method is only one of many possible options.

Return your results as a list of tuples `(post code, item name, amount dispensed as % of total)`. Sort your results ascending alphabetically by post code and take only results from the first 100 post codes.

**NOTE:** Some practices have multiple postal codes associated with them. Use the alphabetically first postal code. Note some postal codes may have multiple `'bnf_name'` with the same prescription rate for the maximum. In this case, take the alphabetically first `'bnf_name'` (as in the PW miniproject).

In [22]:
scripts.head()

,practice,bnf_code,bnf_name,items,nic,act_cost,quantity
0,N85639,0106020C0,Bisacodyl_Tab E/C 5mg,1,0.39,0.47,12
1,N85639,0106040M0,Movicol Plain_Paed Pdr Sach 6.9g,1,4.38,4.07,30
2,N85639,0301011R0,Salbutamol_Inha 100mcg (200 D) CFF,1,1.50,1.40,1
3,N85639,0304010G0,Chlorphenamine Mal_Oral Soln 2mg/5ml,1,2.62,2.44,150
4,N85639,0401020K0,Diazepam_Tab 2mg,1,0.16,0.26,6

In [23]:
practices.head()

,code,name,addr_1,addr_2,borough,village,post_code
0,A81001,THE DENSHAM SURGERY,THE HEALTH CENTRE,LAWSON STREET,STOCKTON ON TEES,CLEVELAND,TS18 1HU
1,A81002,QUEENS PARK MEDICAL CENTRE,QUEENS PARK MEDICAL CTR,FARRER STREET,STOCKTON ON TEES,CLEVELAND,TS18 2AW
2,A81003,VICTORIA MEDICAL PRACTICE,THE HEALTH CENTRE,VICTORIA ROAD,HARTLEPOOL,CLEVELAND,TS26 8DB
3,A81004,WOODLANDS ROAD SURGERY,6 WOODLANDS ROAD,NaN,MIDDLESBROUGH,CLEVELAND,TS1 3BE
4,A81005,SPRINGWOOD SURGERY,SPRINGWOOD SURGERY,RECTORY LANE,GUISBOROUGH,NaN,TS14 7DJ

In [24]:
practice_unique = (practices.sort_values('post_code')
                   .drop_duplicates(subset='code',keep = 'first'))
                   
practice_unique.head()

,code,name,addr_1,addr_2,borough,village,post_code
1896,E82060,PARKBURY HOUSE SURGERY,PARKBURY HOUSE,ST.PETERS STREET,ST.ALBANS,HERTFORDSHIRE,AL1 3HD
1871,E82031,MALTINGS SURGERY,THE MALTINGS SURGERY,8-14 VICTORIA STREET,ST ALBANS,HERTFORDSHIRE,AL1 3JB
1849,E82004,HATFIELD ROAD SURGERY,61 HATFIELD ROAD,NaN,ST.ALBANS,HERTFORDSHIRE,AL1 4JE
1848,E82002,WRAFTON HOUSE SURGERY,WRAFTON HOUSE SURGERY,9/11 WELLFIELD ROAD,HATFIELD,HERTFORDSHIRE,AL10 0BS
9812,Y05146,HCT LYMPHOEDEMA AT WEST ESSEX CCG,QUEENSWAY HEALTH CENTRE,QUEENSWAY,HATFIELD,HERTFORDSHIRE,AL10 0LF

In [25]:
#sorting the post_code and code in order
unique_practices = practices.sort_values('post_code').groupby('code').first().reset_index()
unique_practices.head()

,code,name,addr_1,addr_2,borough,village,post_code
0,A81001,THE DENSHAM SURGERY,THE HEALTH CENTRE,LAWSON STREET,STOCKTON ON TEES,CLEVELAND,TS18 1HU
1,A81002,QUEENS PARK MEDICAL CENTRE,QUEENS PARK MEDICAL CTR,FARRER STREET,STOCKTON ON TEES,CLEVELAND,TS18 2AW
2,A81003,VICTORIA MEDICAL PRACTICE,MCKENZIE HOUSE,17 KENDAL ROAD,HARTLEPOOL,CLEVELAND,TS25 1QU
3,A81004,WOODLANDS ROAD SURGERY,6 WOODLANDS ROAD,ACKLAM,MIDDLESBROUGH,CLEVELAND,TS1 3BE
4,A81005,SPRINGWOOD SURGERY,SPRINGWOOD SURGERY,RECTORY LANE,GUISBOROUGH,NaN,TS14 7DJ

In [26]:
#merging the practicces with the scripts
joined = scripts.merge(unique_practices[['code', 'post_code']], left_on = 'practice', right_on = 'code',how='left')
joined.head()

,practice,bnf_code,bnf_name,items,nic,act_cost,quantity,code,post_code
0,N85639,0106020C0,Bisacodyl_Tab E/C 5mg,1,0.39,0.47,12,N85639,CH44 5UF
1,N85639,0106040M0,Movicol Plain_Paed Pdr Sach 6.9g,1,4.38,4.07,30,N85639,CH44 5UF
2,N85639,0301011R0,Salbutamol_Inha 100mcg (200 D) CFF,1,1.50,1.40,1,N85639,CH44 5UF
3,N85639,0304010G0,Chlorphenamine Mal_Oral Soln 2mg/5ml,1,2.62,2.44,150,N85639,CH44 5UF
4,N85639,0401020K0,Diazepam_Tab 2mg,1,0.16,0.26,6,N85639,CH44 5UF

In [27]:
post_items_total = joined.groupby(['post_code', 'bnf_name'])['items'].sum().reset_index()
post_items_total.head()

  post_code                                  bnf_name  items
0   B11 4BW  3m Health Care_Cavilon Durable Barrier C      7
1   B11 4BW   3m Health Care_Cavilon No Sting Barrier      2
2   B11 4BW      Abasaglar KwikPen_100u/ml 3ml Pf Pen      2
3   B11 4BW                                Abidec_Dps     63
4   B11 4BW                Able Spacer + Sml/Med Mask      1

In [28]:
idx = post_items_total.sort_values('bnf_name').groupby('post_code')['items'].idxmax()
idx.head()

max_items = post_items_total.loc[idx].set_index('post_code')
max_items.head()

                                     bnf_name  items
post_code
B11 4BW    Salbutamol_Inha 100mcg (200 D) CFF    706
B12 9LP                     Paracet_Tab 500mg    425
B18 7AL    Salbutamol_Inha 100mcg (200 D) CFF    556
B21 9RY               Metformin HCl_Tab 500mg   1033
B23 6DJ      Lansoprazole_Cap 30mg (E/C Gran)    599

max_items['index_ratio'] = (max_items['items'] / post_items_total.groupby('post_code')['items'].sum())
max_items.head()

In [30]:
items_by_region = max_items[['bnf_name' , 'index_ratio']][:100]

In [31]:
items_by_region = [tuple(x) for x in items_by_region.to_records(index=True)]

In [32]:
#items_by_region = [("B11 4BW", "Salbutamol_Inha 100mcg (200 D) CFF", 0.0310589063)] * 100

In [33]:
grader.score.dw__items_by_region(items_by_region)

==================
Your score:  1.0
==================

## Question 4: script_anomalies

Drug abuse is a source of human and monetary costs in health care. A first step in identifying practitioners that enable drug abuse is to look for practices where commonly abused drugs are prescribed unusually often. Let's try to find practices that prescribe an unusually high amount of opioids. The opioids we'll look for are given in the list below.

In [34]:
opioids = ['morphine', 'oxycodone', 'methadone', 'fentanyl', 'pethidine', 'buprenorphine', 'propoxyphene', 'codeine']

These are generic names for drugs, not brand names. Generic drug names can be found using the `'bnf_code'` field in `scripts` along with the `chem` table.. Use the list of opioids provided above along with these fields to make a new field in the `scripts` data that flags whether the row corresponds with a opioid prescription.

In [35]:
chem.head()

    CHEM SUB                                NAME
0  0101010A0                     Alexitol Sodium
1  0101010B0                          Almasilate
2  0101010C0                 Aluminium Hydroxide
3  0101010D0  Aluminium Hydroxide With Magnesium
4  0101010E0                        Hydrotalcite

In [36]:
chem = chem.sort_values('CHEM SUB').drop_duplicates(subset='CHEM SUB', keep='first')

In [37]:
scripts.head()

,practice,bnf_code,bnf_name,items,nic,act_cost,quantity
0,N85639,0106020C0,Bisacodyl_Tab E/C 5mg,1,0.39,0.47,12
1,N85639,0106040M0,Movicol Plain_Paed Pdr Sach 6.9g,1,4.38,4.07,30
2,N85639,0301011R0,Salbutamol_Inha 100mcg (200 D) CFF,1,1.50,1.40,1
3,N85639,0304010G0,Chlorphenamine Mal_Oral Soln 2mg/5ml,1,2.62,2.44,150
4,N85639,0401020K0,Diazepam_Tab 2mg,1,0.16,0.26,6

In [38]:
chem['is_opioid'] = chem['NAME'].apply(lambda x: any([opioid in x.lower() for opioid in opioids]))

In [39]:
chem.head()

     CHEM SUB                                NAME  is_opioid
18  010101000    Other Antacid & Simeticone Preps      False
0   0101010A0                     Alexitol Sodium      False
1   0101010B0                          Almasilate      False
2   0101010C0                 Aluminium Hydroxide      False
3   0101010D0  Aluminium Hydroxide With Magnesium      False

In [40]:
scripts_w_opioids = (scripts.merge(chem,left_on = 'bnf_code', right_on = 'CHEM SUB', how='left').fillna(False))
scripts_w_opioids.head()

,practice,bnf_code,bnf_name,items,nic,act_cost,quantity,CHEM SUB,NAME,is_opioid
0,N85639,0106020C0,Bisacodyl_Tab E/C 5mg,1,0.39,0.47,12,0106020C0,Bisacodyl,False
1,N85639,0106040M0,Movicol Plain_Paed Pdr Sach 6.9g,1,4.38,4.07,30,0106040M0,Macrogol 3350,False
2,N85639,0301011R0,Salbutamol_Inha 100mcg (200 D) CFF,1,1.50,1.40,1,0301011R0,Salbutamol,False
3,N85639,0304010G0,Chlorphenamine Mal_Oral Soln 2mg/5ml,1,2.62,2.44,150,0304010G0,Chlorphenamine Maleate,False
4,N85639,0401020K0,Diazepam_Tab 2mg,1,0.16,0.26,6,0401020K0,Diazepam,False

In [41]:
scripts_w_opioids[scripts_w_opioids['is_opioid'].isna()].head()

Empty DataFrame
Columns: [practice, bnf_code, bnf_name, items, nic, act_cost, quantity, CHEM SUB, NAME, is_opioid]
Index: []

Now for each practice calculate the proportion of its prescriptions containing opioids.

**Hint:** Consider the following list: `[0, 1, 1, 0, 0, 0]`. What proportion of the entries are 1s? What is the mean value?

In [42]:
scripts_w_opioids['is_opioid'].isna().sum()

0

In [43]:
scripts_w_opioids.groupby('practice')['is_opioid'].mean()

practice
A81005    0.033179
A81007    0.043329
A81011    0.046556
A81012    0.042793
A81017    0.038140
            ...
Y05570    0.090909
Y05583    0.000000
Y05597    0.000000
Y05660    0.023055
Y05670    0.000000
Name: is_opioid, Length: 856, dtype: float64

In [44]:
opioids_per_practice = scripts_w_opioids.groupby('practice')['is_opioid'].mean()

How do these proportions compare to the overall opioid prescription rate? Subtract off the proportion of all prescriptions that are opioids from each practice's proportion.

In [45]:
relative_opioids_per_practice = opioids_per_practice - scripts_w_opioids['is_opioid'].mean()

Now that we know the difference between each practice's opioid prescription rate and the overall rate, we can identify which practices prescribe opioids at above average or below average rates. However, are the differences from the overall rate important or just random deviations? In other words, are the differences from the overall rate big or small?

To answer this question we have to quantify the difference we would typically expect between a given practice's opioid prescription rate and the overall rate. This quantity is called the **standard error**, and is related to the **standard deviation**, $\sigma$. The standard error in this case is

$$ \frac{\sigma}{\sqrt{n}} $$

where $n$ is the number of prescriptions each practice made. Calculate the standard error for each practice. Then divide `relative_opioids_per_practice` by the standard errors. We'll call the final result `opioid_scores`.

In [46]:
sigma = scripts_w_opioids['is_opioid'].std()

In [47]:
counts_per_practice = scripts_w_opioids['practice'].value_counts()

In [48]:
standard_error_per_practice = sigma / counts_per_practice ** 0.5
opioid_scores = relative_opioids_per_practice / standard_error_per_practice

In [49]:
opioid_scores

A81005   -0.548306
A81007    1.544557
A81011    2.291795
A81012    1.373060
A81017    0.583168
            ...
Y05570    1.391142
Y05583   -1.019657
Y05597   -0.817544
Y05660   -1.278102
Y05670   -0.667522
Length: 856, dtype: float64

The quantity we have calculated in `opioid_scores` is called a **z-score**:

$$ \frac{\bar{X} - \mu}{\sqrt{\sigma^2/n}} $$

Here $\bar{X}$ corresponds with the proportion for each practice, $\mu$ corresponds with the proportion across all practices, $\sigma^2$ corresponds with the variance of the proportion across all practices, and $n$ is the number of prescriptions made by each practice. Notice $\bar{X}$ and $n$ will be different for each practice, while $\mu$ and $\sigma$ are determined across all prescriptions, and so are the same for every z-score. The z-score is a useful statistical tool used for hypothesis testing, finding outliers, and comparing data about different types of objects or events.

Now that we've calculated this statistic, take the 100 practices with the largest z-score. Return your result as a list of tuples in the form `(practice_name, z-score, number_of_scripts)`. Sort your tuples by z-score in descending order. Note that some practice codes will correspond with multiple names. In this case, use the first match when sorting names alphabetically.

In [50]:
unique_practices = practices.sort_values('name').drop_duplicates(subset='code', keep='first')
unique_practices.head()
#anomalies = [("NATIONAL ENHANCED SERVICE", 11.6958178629, 7)] * 100

,code,name,addr_1,addr_2,borough,village,post_code
7012,P87657,(IRLAM) SALFORD CARE CTRS MEDICAL PRACTI,SALFORD CARE CTR(IRLAM),125 LIVERPOOL ROAD,IRLAM,MANCHESTER,M44 6DP
10922,Y05381,0-19 EAST CHESHIRE HEALTH VISITORS,SALINAE CLINIC,LEWIN STREET,MIDDLEWICH,CHESHIRE,CW10 9FG
11984,Y04082,0-19 PUBLIC HEALTH SERVICE HARTLEPOOL,CHATHAM CHILDRENS CENTRE,29 CHATHAM ROAD,HARTLEPOOL,NaN,TS24 8QG
7573,Y00364,1 TO 1 CENTRE,BRENKLEY AVENUE,SHIREMOOR,NEWCASTLE UPON TYNE,NaN,NE27 0PR
6836,P87652,1/LOWER BROUGHTON MEDICAL PRACTICE,LOWER BROUGHTON HTH.CTR.,GREAT CLOWES STREET,SALFORD,NaN,M7 1RD

In [51]:
unique_practices = unique_practices.set_index('code')

In [52]:
unique_practices['z_score'] = opioid_scores
unique_practices['counts'] = counts_per_practice

In [53]:
anomalies = unique_practices[['name', 'z_score', 'counts']].sort_values('z_score', ascending= False)

anomalies.head()

                                   name    z_score  counts
code
Y01852        NATIONAL ENHANCED SERVICE  11.695818     7.0
Y03006         OUTREACH SERVICE NH / RH   7.339043     2.0
Y03668  BRISDOC HEALTHCARE SERVICES OOH   6.150582    60.0
G81703           H&R P C SPECIAL SCHEME   5.123032    36.0
Y04997                   HMR BARDOC OOH   4.958866   321.0

In [54]:
#results.head()

In [57]:
grader.score.dw__script_anomalies(anomalies.head(100))

==================
Your score:  1.0
==================

## Question 5: script_growth

Another way to identify anomalies is by comparing current data to historical data. In the case of identifying sites of drug abuse, we might compare a practice's current rate of opioid prescription to their rate 5 or 10 years ago. Unless the nature of the practice has changed, the profile of drugs they prescribe should be relatively stable. We might also want to identify trends through time for business reasons, identifying drugs that are gaining market share. That's what we'll do in this question.

We'll load in beneficiary data from 6 months earlier, June 2016, and calculate the percent growth in prescription rate from June 2016 to January 2017 for each `bnf_name`. We'll return the 50 items with largest growth and the 50 items with the largest shrinkage (i.e. negative percent growth) as a list of tuples sorted by growth rate in descending order in the format `(script_name, growth_rate, raw_2016_count)`. You'll notice that many of the 50 fastest growing items have low counts of prescriptions in 2016. Filter out any items that were prescribed less than 50 times.

In [58]:
scripts16 = pd.read_csv('./dw-data/201606scripts_sample.csv.gz')
scripts16.head()

,practice,bnf_code,bnf_name,items,nic,act_cost,quantity
0,N85638,0301011R0,Salamol_Inha 100mcg (200 D) CFF (Teva),2,2.92,2.73,2
1,N85638,0301011R0,Easyhaler_Salbutamol Sulf 200mcg (200D),1,6.63,6.15,1
2,N85638,0301020I0,Ipratrop Brom_Inh Soln 500mcg/2ml Ud,1,1.77,1.75,12
3,N85638,0301020I0,Ipratrop Brom_Inh Soln 250mcg/1ml Ud,1,4.47,4.15,20
4,N85638,0302000C0,Clenil Modulite_Inha 50mcg (200D),1,3.70,3.44,1

In [59]:
scripts.groupby('bnf_name')['items'].sum()

bnf_name
365 Film 10cm x 12cm VP Adh Film Dress       2
365 Non Adherent 10cm x 10cm Pfa Plas Fa     3
365 Non Adherent 10cm x 20cm Pfa Plas Fa     1
365 Non Woven Island 8cm x 10cm Adh Dres     1
365 Transpt Island 5cm x 7.2cm VP Adh Fi     2
                                            ..
nSpire PiKo-1 Stnd Range Peak Flow Meter     1
nSpire Pocket Peak Low Range Peak Flow M     4
nSpire Pocket Peak Stnd Range Peak Flow      8
oraNurse_Toothpaste Orig (1450ppm)           4
palmdoc (Reagent)_Strips                    59
Name: items, Length: 13471, dtype: int64

In [60]:
pct_growth = (scripts['bnf_name'].value_counts() / scripts16['bnf_name'].value_counts()) -1

In [61]:
pct_growth = pct_growth.rename('pct_growth')

In [62]:
df_script_growth = (pct_growth
                   .rename('pct_growth')
                   .to_frame()
                   .assign(raw_counts = scripts16['bnf_name'].value_counts())
                   .query('raw_counts >=50')
                   .dropna()
                   .reset_index()
                   .rename({'index':'bnf_name'}, axis=1)
                   .sort_values('pct_growth', ascending = False))
df_script_growth.head()

                                      bnf_name  pct_growth  raw_counts
431            Butec_Transdermal Patch 5mcg/hr    3.467742        62.0
430           Butec_Transdermal Patch 10mcg/hr    3.000000        69.0
1409  Fostair NEXThaler_Inh 200mcg/6mcg (120D)    1.430233        86.0
2612     Pneumococcal_Vac 0.5ml Vl (23 Valent)    1.269430       193.0
3033  Spiolto Respimat_Inha2.5/2.5mcg(60D)+Dev    1.269231        52.0

In [63]:
df_script_growth.head(50)

                                      bnf_name  pct_growth  raw_counts
431            Butec_Transdermal Patch 5mcg/hr    3.467742        62.0
430           Butec_Transdermal Patch 10mcg/hr    3.000000        69.0
1409  Fostair NEXThaler_Inh 200mcg/6mcg (120D)    1.430233        86.0
2612     Pneumococcal_Vac 0.5ml Vl (23 Valent)    1.269430       193.0
3033  Spiolto Respimat_Inha2.5/2.5mcg(60D)+Dev    1.269231        52.0
3257          Trulicity_Inj 1.5mg/0.5ml Pf Pen    1.185185        54.0
854           CosmoCol_Paed Oral Pdr Sach 6.9g    1.177419        62.0
1077        Dulaglutide_Inj 1.5mg/0.5ml Pf Dev    0.963415        82.0
3375   ViATIM_Vac D/Chamber 160u/25mcg 1ml Pfs    0.912000       125.0
1140                    Empagliflozin_Tab 25mg    0.896000       125.0
503           CareSens Lancets 0.31mm/30 Gauge    0.895522        67.0
1411        Fostair_Inh 200mcg/6mcg (120D) CFF    0.861660       253.0
2462   Orbis Nor Saline Sod Chlor 0.9% Nsl Dps    0.858824        85.0
3282         Umeclidinium Brom_Inh 65mcg (30D)    0.827586        87.0
3279      Ultibro Breezhaler_Pdr Inh Cap + Dev    0.801653       121.0
2041                     Medihoney_Barrier Crm    0.784091        88.0
1346     Fluoxetine HCl_Oral Soln 20mg/5ml S/F    0.780822        73.0
3095                     TEE2 (Reagent)_Strips    0.777778        81.0
3430                      Zaluron XL_Tab 400mg    0.758621        58.0
1873      Laxido_Paed Plain Oral Pdr Sach 6.9g    0.758621       174.0
2641         Prednisolone_Oral Soln 5mg/5ml Ud    0.726027        73.0
416        Buprenorphine_Patch 15mcg/hr (7day)    0.715596       109.0
795   Coloplast_SenSura Mio Maxi Drnbl Bag S/C    0.703704        81.0
2382           Octenisan_Antimicrobial Wsh Lot    0.702703        74.0
1076        Duaklir Genuair_340mcg/12mcg (60D)    0.671053       152.0
2992      Sod Chlor_Inh Soln 0.9% 2.5ml Ud Amp    0.641975       162.0
794   Coloplast_SenSura Mio Maxi Drnbl Bag L/C    0.627451        51.0
1375            Flutiform_Inha 50/5mcg (120 D)    0.625000        88.0
1688           Ins Degludec_100u/ml 3ml Pf Pen    0.616667        60.0
504           CareSens Lancets 0.36mm/28 Gauge    0.611111        90.0
1177                           Epimax Crm 500g    0.610000       100.0
1243             Evacal D3_Tab Chble 400u/1.5g    0.604651        86.0
2946                          Shortec_Cap 20mg    0.602941        68.0
717   Co-Trimoxazole_Oral Susp 40/200mg/5mlS/F    0.600000        50.0
595      Ciprofloxacin_Gran For Susp 250mg/5ml    0.592105        76.0
71    AgaMatrix Ultra-Thin Lancets 0.35mm/28 G    0.566038        53.0
3436                  Zemtard 120 XL_Cap 120mg    0.563636        55.0
2370                    Nutramigen 2 + LGG_Pdr    0.560440        91.0
3210      Toujeo_300u/ml 1.5ml Pf SoloStar Pen    0.540881       159.0
1722  Ins Tresiba_FlexTouch 100u/ml 3ml Pf Pen    0.540541       148.0
1954                      Longtec_Tab 30mg M/R    0.537037       108.0
44                              Adalat_Cap 5mg    0.536585        82.0
953             Dexameth_Oral Soln 2mg/5ml S/F    0.529412        68.0
1574            Haloperidol_Inj 5mg/ml 1ml Amp    0.528846       104.0
1989                     Lyclear_Dermal Crm 5%    0.521127        71.0
3334        Valupak_Multivit & Mineral Tab OAD    0.509804        51.0
800   Coloplast_Sensura Mio Maxi Clsd Bag + Fl    0.505618        89.0
2042                     Medikinet XL_Cap 10mg    0.484848        99.0
1056                        Dovobet_Gel Applic    0.481481        54.0
1674           Incruse Ellipta_Inh 55mcg (30D)    0.480769       208.0

In [64]:
df_script_growth.tail(50)

                                      bnf_name  pct_growth  raw_counts
2505                Oxycodone HCl_Tab 20mg M/R   -0.431818       264.0
499                         Cardura XL_Tab 4mg   -0.434783        69.0
2510                Oxycodone HCl_Tab 80mg M/R   -0.435897        78.0
3364               Verapamil HCl_Cap 120mg M/R   -0.437908       153.0
3199                         Topamax_Tab 100mg   -0.451613        62.0
2448               Opticrom_Allergy Eye Dps 2%   -0.452381       126.0
2455                    Optilast_Eye Dps 0.05%   -0.454545        55.0
37                Actonel_Once a Week Tab 35mg   -0.457627        59.0
2665                  Premique_Tab 0.625mg/5mg   -0.470395       304.0
3072           Sunsense_Daily Face Crm Spf 50+   -0.483444       151.0
1602        Hydrocort/Crotamiton_Crm 0.25%/10%   -0.489362       141.0
257            Azelastine HCl_Aq Eye Dps 0.05%   -0.503623       276.0
2449                  Opticrom_Eye Dps 2% (Aq)   -0.507389       203.0
2134             Metoprolol Tart_Tab 200mg M/R   -0.509091        55.0
2779                        Rapitil_Eye Dps 2%   -0.509677       155.0
937      Desloratadine_Oral Soln 2.5mg/5ml S/F   -0.514706       136.0
1195           Erythromycin_Ethylsuc Tab 500mg   -0.515464        97.0
177   Aquacel Foam Adhesive 8cm x 8cm Wound Dr   -0.529412        68.0
3458                   Zirtek_Allergy Tab 10mg   -0.530303        66.0
152      Antaz Sulf/Xylomet_Eye Dps 0.5%/0.05%   -0.545455        66.0
3396               Vital 1.5kcal_Liq (Vanilla)   -0.546667        75.0
2488    Oxybutynin HCl_Oral Soln 2.5mg/5ml S/F   -0.557377        61.0
2634                   Prazosin HCl_Tab 500mcg   -0.558140        86.0
194                 Artificial Saliva_Spy 50ml   -0.558685       213.0
3074                Sunsense_Ultra Lot Spf 50+   -0.565217       368.0
3132                     Telfast 120_Tab 120mg   -0.569892        93.0
2468                 Otrivine-Antistin_Eye Dps   -0.572464       138.0
1305                 Fexofenadine HCl_Tab 30mg   -0.595960       297.0
2016                            Mag Trisil_Mix   -0.611940        67.0
1480                     Glibenclamide_Tab 5mg   -0.616438       146.0
710               Co-Danthrusate_Cap 50mg/60mg   -0.629630        81.0
1832         Ketotifen Fumar_Eye Dps 250mcg/ml   -0.684211        57.0
3317                    Uvistat_Sun Crm Spf 50   -0.691729       133.0
1571                  Haelan_Tape 7.5cm x 50cm   -0.713043       115.0
1570                  Haelan_Tape 7.5cm x 20cm   -0.720000       100.0
307    Beconase_Hayfever Nsl Spy 50mcg (180 D)   -0.738462        65.0
3316                    Uvistat_Sun Crm Spf 30   -0.764706        68.0
912                    Deep Freeze_Cold Gel 2%   -0.775862        58.0
60                         Adizem-SR_Tab 120mg   -0.826923        52.0
153                            Anugesic HC_Crm   -0.854167        96.0
3073         Sunsense_Sunsensitive Crm SPF 50+   -0.856209       153.0
1584      Hepatyrix_Vac 1440u/25mcg/ml 1ml Pfs   -0.875000       216.0
624                          Climagest_Tab 2mg   -0.893939        66.0
626                           Climaval_Tab 2mg   -0.901515       132.0
2464                 Orphenadrine HCl_Tab 50mg   -0.911765       102.0
1623        Hydroxyzine HCl_Oral Soln 10mg/5ml   -0.914894        94.0
2471                               Ovysmen_Tab   -0.925373        67.0
625                           Climaval_Tab 1mg   -0.926471       136.0
627                               Climesse_Tab   -0.942029        69.0
2613                      Polyalc_Eye Dps 1.4%   -0.996324       272.0

In [65]:
script_growth = pd.concat([df_script_growth.head(50),df_script_growth.tail(50)])

In [66]:
#script_growth = [("Butec_Transdermal Patch 5mcg\/hr", 3.4677419355, 62.0)] * 100

In [67]:
grader.score.dw__script_growth(script_growth)

==================
Your score:  1.0
==================

## Question 6: rare_scripts

Does a practice's prescription costs originate from routine care or from reliance on rarely prescribed treatments? Commonplace treatments can carry lower costs than rare treatments because of efficiencies in large-scale production. While some specialist practices can't help but avoid prescribing rare medicines because there are no alternatives, some practices may be prescribing a unnecessary amount of brand-name products when generics are available. Let's identify practices whose costs disproportionately originate from rarely prescribed items.

First we have to identify which `'bnf_code'` are rare. To do this, find the probability $p$ of a prescription having a particular `'bnf_code'` if the `'bnf_code'` was randomly chosen from the unique options in the beneficiary data. We will call a `'bnf_code'` rare if it is prescribed at a rate less than $0.1p$.

In [68]:
p = 1 / scripts['bnf_code'].nunique()
rates = scripts['bnf_code'].value_counts() / scripts.shape[0]
rare_codes = rates < 0.1 * p
scripts = ( scripts
           .set_index('bnf_code')
          .assign(rare=rare_codes)
          .reset_index())
#scripts['rare'] = rare_codes

In [69]:
scripts.head()

,bnf_code,practice,bnf_name,items,nic,act_cost,quantity,rare
0,0106020C0,N85639,Bisacodyl_Tab E/C 5mg,1,0.39,0.47,12,False
1,0106040M0,N85639,Movicol Plain_Paed Pdr Sach 6.9g,1,4.38,4.07,30,False
2,0301011R0,N85639,Salbutamol_Inha 100mcg (200 D) CFF,1,1.50,1.40,1,False
3,0304010G0,N85639,Chlorphenamine Mal_Oral Soln 2mg/5ml,1,2.62,2.44,150,False
4,0401020K0,N85639,Diazepam_Tab 2mg,1,0.16,0.26,6,False

In [70]:
rare_cost_total = (scripts
                  .query('rare==True')
                  .groupby('practice')['act_cost']
                  .sum())
rare_cost_total

practice
A81005    1247.83
A81007     951.06
A81011     816.02
A81012    1145.11
A81017    1712.15
           ...
Y05434    5918.27
Y05435    2428.19
Y05438     762.02
Y05493      40.89
Y05660       2.83
Name: act_cost, Length: 766, dtype: float64

Now for each practice, calculate the proportion of costs that originate from prescription of rare treatments (i.e. rare `'bnf_code'`). Use the `'act_cost'` field for this calculation.

In [71]:
all_cost_total = scripts.groupby('practice')['act_cost'].sum()

all_cost_total

practice
A81005    103840.82
A81007    113482.49
A81011    159507.03
A81012     83296.81
A81017    232656.17
            ...
Y05570        86.76
Y05583      1610.16
Y05597        90.41
Y05660      8762.51
Y05670        36.95
Name: act_cost, Length: 856, dtype: float64

In [72]:
# NaN might happen from division by zero
# there are some practice that don't have rare drugs prescribed
rare_cost_total / all_cost_total

practice
A81005    0.012017
A81007    0.008381
A81011    0.005116
A81012    0.013747
A81017    0.007359
            ...
Y05570         NaN
Y05583         NaN
Y05597         NaN
Y05660    0.000323
Y05670         NaN
Name: act_cost, Length: 856, dtype: float64

In [73]:
rare_cost_prop = (rare_cost_total /  all_cost_total).fillna(0)

Now we will calculate a z-score for each practice based on this proportion.
First take the difference of `rare_cost_prop` and the proportion of costs originating from rare treatments across all practices.

In [74]:
relative_rare_cost_prop = (rare_cost_prop - 
                           scripts.query('rare==True')['act_cost'].sum() / scripts['act_cost'].sum())

Now we will estimate the standard errors (i.e. the denominator of the z-score) by simply taking the standard deviation of this difference.

In [75]:
standard_errors = relative_rare_cost_prop.std()

Finally compute the z-scores. Return the practices with the top 100 z-scores in the form `(post_code, practice_name, z-score)`. Note that some practice codes will correspond with multiple names. In this case, use the first match when sorting names alphabetically.

In [76]:
rare_scores = (relative_rare_cost_prop / standard_errors).rename('rare_score')

In [77]:
rare_scores

practice
A81005   -0.065216
A81007   -0.125308
A81011   -0.179263
A81012   -0.036615
A81017   -0.142190
            ...
Y05570   -0.263811
Y05583   -0.263811
Y05597   -0.263811
Y05660   -0.258473
Y05670   -0.263811
Name: rare_score, Length: 856, dtype: float64

In [78]:
practice_unique.head()

,code,name,addr_1,addr_2,borough,village,post_code
1896,E82060,PARKBURY HOUSE SURGERY,PARKBURY HOUSE,ST.PETERS STREET,ST.ALBANS,HERTFORDSHIRE,AL1 3HD
1871,E82031,MALTINGS SURGERY,THE MALTINGS SURGERY,8-14 VICTORIA STREET,ST ALBANS,HERTFORDSHIRE,AL1 3JB
1849,E82004,HATFIELD ROAD SURGERY,61 HATFIELD ROAD,NaN,ST.ALBANS,HERTFORDSHIRE,AL1 4JE
1848,E82002,WRAFTON HOUSE SURGERY,WRAFTON HOUSE SURGERY,9/11 WELLFIELD ROAD,HATFIELD,HERTFORDSHIRE,AL10 0BS
9812,Y05146,HCT LYMPHOEDEMA AT WEST ESSEX CCG,QUEENSWAY HEALTH CENTRE,QUEENSWAY,HATFIELD,HERTFORDSHIRE,AL10 0LF

In [89]:
output = practice_unique.merge(rare_scores, left_on = 'code', right_index = True).reset_index()

output= (output[['code', 'name', 'rare_score']]
               .sort_values('rare_score', ascending = False).head(100))

In [90]:
practice_names = practices.groupby('code')['name'].unique().apply(min)
result = (pd.concat([practice_names, rare_scores], axis=1, sort=False)
            .nlargest(100, 'rare_score')
            .reset_index())
rare_scripts = [tuple(x) for x in result.to_records(index=False)]

In [94]:
rare_scripts[:5]

[('Y03472', 'CONSULTANT DIABETES TEAM', 16.262687124655073),
 ('Y05320', 'DMC COMMUNITY DERMATOLOGY RBWF', 15.128648195416869),
 ('Y04404', 'OUTPATIENTS JUBILEE HEALTH CENTRE', 7.54213935610462),
 ('Y03484', 'DMC COMMUNITY DERMATOLOGY CLINIC', 7.287222200297828),
 ('Y04424', 'DMC HEALTHCARE', 6.838614181432866)]

In [95]:
#rare_scripts = [("Y03472", "CONSULTANT DIABETES TEAM", 16.2626871247)] * 100

In [96]:
grader.score.dw__rare_scripts(rare_scripts)

==================
Your score:  1.0
==================

*Copyright &copy; 2020 The Data Incubator.  All rights reserved.*